services:
  backend:
    build:
      context: ./backend
    container_name: rehab-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=app
      - CHROMA_PATH=/data/chroma
      # - OPENAI_API_KEY=your_key
      - CORS_ALLOW_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
    ports:
      - "8000:8000"
    volumes:
      - chroma:/data/chroma
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: rehab-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
  chroma:




